DIR_MODULE_INTERFACE		:= Interface
DIR_INTERFACE_INTERFACE	:= $(DIR_MODULE_INTERFACE)
DIR_INTERNAL_INTERFACE	:= $(DIR_MODULE_INTERFACE)/_internal

SRC_INTERFACE_INTERFACE	:= Interface.c 
SRC_INTERNAL_INTERFACE	:= 

OBJ_INTERFACE			:= $(addprefix $(DIR_OBJ)/$(DIR_INTERFACE_INTERFACE)/, $(SRC_INTERFACE_INTERFACE:.c=.o))
OBJ_INTERFACE			+= $(addprefix $(DIR_OBJ)/$(DIR_INTERNAL_INTERFACE)/, $(SRC_INTERNAL_INTERFACE:.c=.o))

$(DIR_OBJ)/$(DIR_MODULE_INTERFACE)/%.o: $(DIR_SRC)/$(DIR_MODULE_INTERFACE)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(DEBUGFLAGS) $(INCLUDE_ALL) -I$(DIR_SRC)/$(DIR_MODULE_INTERFACE)/_internal -c $< -o $@
