DIR_MODULE_PARSEUR		:= Parseur
DIR_INTERFACE_PARSEUR	:= $(DIR_MODULE_PARSEUR)
DIR_INTERNAL_PARSEUR	:= $(DIR_MODULE_PARSEUR)/_internal

SRC_INTERFACE_PARSEUR	:= Parseur.c 
SRC_INTERNAL_PARSEUR	:= 

OBJ_PARSEUR			:= $(addprefix $(DIR_OBJ)/$(DIR_INTERFACE_PARSEUR)/, $(SRC_INTERFACE_PARSEUR:.c=.o))
OBJ_PARSEUR			+= $(addprefix $(DIR_OBJ)/$(DIR_INTERNAL_PARSEUR)/, $(SRC_INTERNAL_PARSEUR:.c=.o))

$(DIR_OBJ)/$(DIR_MODULE_PARSEUR)/%.o: $(DIR_SRC)/$(DIR_MODULE_PARSEUR)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $(DEBUGFLAGS) $(INCLUDE_ALL) -I$(DIR_SRC)/$(DIR_MODULE_PARSEUR)/_internal -c $< -o $@
